import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('ps'),
    Locale('fa'),
    Locale('ur'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    if (key.endsWith(' *')) {
      return '${t(key.substring(0, key.length - 2))} *';
    }
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'Post for a customer': 'Post for a customer',
      'Customer Name': 'Customer Name',
      'Customer WhatsApp Number': 'Customer WhatsApp Number',
      'The ad goes into the customer account for this number.': 'The ad goes into the customer account for this number.',
      'e.g. Ahmed Khan': 'e.g. Ahmed Khan',
      'exterior_color': 'Exterior Color',
      'interior_color': 'Interior Color',
      'regional_specs': 'Regional Specs',
      'seller_no_whatsapp': 'This seller has not added a WhatsApp number.',
      'whatsapp_not_installed': 'Could not open WhatsApp.',
      'home': 'HOME',
      'chats': 'CHATS',
      'sell': 'SELL',
      'my_ads': 'MY ADS',
      'account': 'ACCOUNT',
      'profile': 'Profile',
      'account_settings': 'Account Settings',
      'notifications': 'Notifications',
      'country': 'Country',
      'language': 'Language',
      'help_support': 'Help & Support',
      'choose_category': 'Choose a category',
      'post_an_ad': 'Post an Ad',
      'category_cars': 'Cars',
      'used_cars': 'Used Cars',
      'new_cars': 'New Cars',
      'export_cars': 'Export Cars',
      'rental_cars': 'Rental Cars',
      'new': 'New',
      'category_properties': 'Properties',
      'category_mobiles': 'Mobiles',
      'category_spare_parts': 'Spare Parts',
      'category_electronics': 'Electronics/Appliances',
      'category_furniture': 'Furniture',
      'category_classifieds': 'Classifieds',
      'category_jobs': 'Jobs',
      'category_coming_soon': '{category} category screen will be enabled soon.',
      'find_listings': 'Find listings',
      'find_listings_desc':
          'Select a country, open a category, then use search, filter, and sort to narrow results.',
      'post_ad': 'Post an ad',
      'post_ad_desc':
          'Tap the center plus button, choose a category, fill details, and submit for review.',
      'chat_with_sellers': 'Chat with sellers',
      'chat_with_sellers_desc':
          'Open a listing and tap Chat. You can block or report users from chat profile.',
      'call': 'Call',
      'email': 'Email',
      'select_country': 'Select Country',
      'search': 'Search',
      'discover': 'Discover AFGHAN DEALS PRO Deal',
      'clear_all': 'Clear All',
      'apply': 'Apply',
      'filter': 'Filter',
      'sort_by': 'Sort By',
      'all': 'All',
      'latest': 'Latest',
      'most_popular': 'Most Popular',
      'popular': 'Popular',
      'verified_sort': 'Verified',
      'mobile_phones': 'Mobile Phones',
      'all_classifieds': 'All Classifieds',
      'newest_to_oldest': 'Newest to Oldest',
      'oldest_to_newest': 'Oldest to Newest',
      'price_highest_to_lowest': 'Price Highest to Lowest',
      'price_lowest_to_highest': 'Price Lowest to Highest',
      'body_type': 'Body Type',
      'year_range': 'Year Range',
      'from': 'From',
      'to': 'To',
      'results': 'results',
      'search_cars': 'Search cars...',
      'all_cars': 'All Cars',
      'add_listings_from_admin_dashboard': 'Add listings from admin dashboard',
      'makes': 'Makes',
      'models': 'Models',
      'sub_models': 'Sub-Models',
      'specs': 'Specs',
      'deal_type': 'Deal Type',
      'ext_color': 'Ext. Color',
      'driveline': 'Driveline',
      'cylinders': 'Cylinders',
      'int_color': 'Int. Color',
      'region': 'Region',
      'price_range': 'Price Range',
      'max_price_aed': 'Max price AED',
      'min_price_aed': 'Min price AED',
      'chat': 'Chat',
      'share_listing': 'Share Listing',
      'copy_to_clipboard': 'Copy to Clipboard',
      'copy_link': 'Copy Link',
      'english': 'English',
      'pashto': 'Pashto',
      'dari': 'Dari (Persian)',
      'urdu': 'Urdu',
      'verified': 'Verified',
      'get_verified': 'Get Verified',
      'joined_on': 'Joined on {date}',
      'guest': 'Guest',
      'log_out': 'Log Out',
      'cancel': 'Cancel',
      'logout_confirm': 'Are you sure you want to log out?',
      'help': 'Help',
      'welcome_title': 'Welcome to AFGHAN DEALS PRO',
      'welcome_subtitle': 'The trusted community of\nbuyers and sellers',
      'continue_phone': 'Continue with Phone',
      'continue_google': 'Continue with Google',
      'sign_in_apple': 'Sign in with Apple',
      'or': 'OR',
      'login_email': 'Login with Email',
      'terms_intro': 'If you continue, you are accepting\n',
      'terms_text': 'AFGHAN DEALS PRO Terms and Conditions\nand Privacy Policy',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'create_password': 'Create a password (min 6 chars)',
      'dont_have_account': "Don't have an account? ",
      'already_have_account': 'Already have an account? ',
      'change_password': 'Change Password',
      'privacy': 'Privacy',
      'blocked_users': 'Blocked Users',
      'danger_zone': 'Danger Zone',
      'deactivate_account': 'Deactivate Account',
      'delete_account': 'Delete Account',
      'Basic Info': 'Basic Info',
      'Ad Type': 'Ad Type',
      'Ad Details': 'Ad Details',
      'Mobile Details': 'Mobile Details',
      'Car Details': 'Car Details',
      'Property Details': 'Property Details',
      'Price': 'Price',
      'Price & Location': 'Price & Location',
      'Location': 'Location',
      'Contact & Amenities': 'Contact & Amenities',
      'Title': 'Title',
      'Description': 'Description',
      'Subcategory': 'Subcategory',
      'Property Type': 'Property Type',
      'Purpose': 'Purpose',
      'Furnishing': 'Furnishing',
      'Bedrooms': 'Bedrooms',
      'Bathrooms': 'Bathrooms',
      'Area (sqft)': 'Area (sqft)',
      'Seller Name': 'Seller Name',
      'Phone': 'Phone',
      'Amenities (comma separated)': 'Amenities (comma separated)',
      'Brand': 'Brand',
      'Model': 'Model',
      'Condition': 'Condition',
      'Storage': 'Storage',
      'RAM': 'RAM',
      'Age': 'Age',
      'Screen Size': 'Screen Size',
      'Color': 'Color',
      'Warranty': 'Warranty',
      'Battery Health': 'Battery Health',
      'Version': 'Version',
      'Damage / Defects': 'Damage / Defects',
      'Seller Type': 'Seller Type',
      'Rental Duration': 'Rental Duration',
      'Make (Brand)': 'Make (Brand)',
      'Year': 'Year',
      'Mileage (km)': 'Mileage (km)',
      'Transmission': 'Transmission',
      'Fuel Type': 'Fuel Type',
      'Body Type': 'Body Type',
      'Exterior Color': 'Exterior Color',
      'Currency': 'Currency',
      'City': 'City',
      'Address': 'Address',
      'Post Ad': 'Post Ad',
      'Photos': 'Photos',
      'Add Photo': 'Add Photo',
      'Cover': 'Cover',
      'Choose from Gallery': 'Choose from Gallery',
      'Take a Photo': 'Take a Photo',
      'First photo will be the cover. Tap + to add up to 10 photos.':
          'First photo will be the cover. Tap + to add up to 10 photos.',
      // Common
      'no_listings_yet': 'No listings yet',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'edit': 'Edit',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      // Chat
      'say_hi_to_start': 'Say hi to start chat',
      'seen': 'Seen',
      'delete_chat': 'Delete Chat',
      'your_chat_is_empty': 'Your chat is empty!',
      'open_listing_and_tap_chat': 'Open a listing and tap Chat to start conversation',
      'explore_listings': 'Explore Listings',
      'block_user': 'Block User',
      'unblock_user': 'Unblock User',
      'user_blocked_chat_disabled': 'User blocked. Chat is disabled.',
      'user_unblocked_chat_enabled': 'User unblocked. Chat is enabled.',
      'report_user': 'Report User',
      'report_submitted': 'Report submitted to admin.',
      'chat_listing': 'Chat Listing',
      'user_profile': 'User Profile',
      'message': 'Type message...',
      'account_restricted': 'Your account has been restricted from sending messages.',
      'user_blocked_unblock_to_chat': 'This user is blocked. Unblock from user profile to continue chat.',
      'listings': 'Listings',
      'member_since': 'Member Since',
      'reporting': 'Reporting',
      'report': 'Report',
      'blocking': 'Blocking',
      'block': 'Block',
      'blocked': 'Blocked',
      'not_shared': 'Not shared',
      'location': 'Location',
      'location_not_shared': 'Location not shared',
      'phone': 'Phone',
      // Profile
      'profile_name': 'Profile Name',
      'displayed_on_profile': 'This is displayed on your profile',
      'account_details': 'Account details',
      'not_visible_to_others': 'This is not visible to other users',
      'save_changes': 'Save Changes',
      'profile_saved_successfully': 'Profile saved successfully!',
      'failed_to_save': 'Failed to save',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'date_of_birth': 'Date of Birth',
      'select_date_of_birth': 'Select date of birth',
      'nationality': 'Nationality',
      'select_nationality': 'Select nationality',
      'gender': 'Gender',
      'select_gender': 'Select gender',
      'male': 'Male',
      'female': 'Female',
      'prefer_not_to_say': 'Prefer not to say',
      'update_password': 'Update Password',
      'deactivate': 'Deactivate',
      'delete_account_confirm': 'Delete Account',
      'blocked_users_list': 'Blocked Users',
      'no_blocked_users': 'No blocked users',
      'unblock': 'Unblock',
      'push_notifications': 'Push Notifications',
      'enable_all_notifications': 'Enable all push notifications',
      'upload_failed': 'Upload failed',
      'my_profile': 'My Profile',
      'block_user_desc': 'You can report this user to admin and keep the chat closed.',
      'unblock_user_desc': 'This user will be able to chat with you again.',
      'new_password': 'New Password',
      'confirm_password': 'Confirm New Password',
      'passwords_not_match': 'Passwords do not match.',
      'password_updated': 'Password updated successfully.',
      'deactivate_account_desc': 'Your account, listings, and profile will be hidden. You can reactivate later by contacting support/admin.',
      'delete_account_desc': 'This will permanently delete your account and all your data. This action cannot be undone.',
      'user_unblocked': 'User unblocked.',
      // Auth
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'name_required': 'Name is required',
      'email_required': 'Email is required',
      'valid_email_required': 'Enter a valid email',
      'phone_number': 'Phone Number',
      'eg_phone': 'e.g. +93700000000',
      'password_required': 'Password is required',
      'min_6_characters': 'Minimum 6 characters',
      'select_country_code': 'Select Country Code',
      'send_code': 'Send Code',
      'enter_verification_code': 'Enter verification\ncode',
      'submit': 'Submit',
      'welcome_back': 'Welcome Back',
      'sign_in_to_account': 'Sign in to your account',
      'enter_email': 'Enter your email',
      'fill_details_to_start': 'Fill in your details to get started',
      'afghanistan': 'Afghanistan',
      'pakistan': 'Pakistan',
      'iran': 'Iran',
      'india': 'India',
      'bangladesh': 'Bangladesh',
      'turkey': 'Turkey',
      'saudi_arabia': 'Saudi Arabia',
      'oman': 'Oman',
      'qatar': 'Qatar',
      'ksa': 'Saudi Arabia',
      'syria': 'Syria',
      'uae_short': 'UAE',
      'uae': 'United Arab Emirates',
      'usa': 'United States',
      'uk': 'United Kingdom',
      'china': 'China',
      'russia': 'Russia',
      'germany': 'Germany',
      'france': 'France',
      'canada': 'Canada',
      'australia': 'Australia',
      'japan': 'Japan',
      'korea': 'South Korea',
      'malaysia': 'Malaysia',
      'indonesia': 'Indonesia',
      'egypt': 'Egypt',
      'nigeria': 'Nigeria',
      'kenya': 'Kenya',
      'south_africa': 'South Africa',
      'other': 'Other',
      // Admin
      'all_chats': 'All Chats',
      'access_denied': 'Access Denied',
      'no_chats_yet': 'No chats yet.',
      'no_messages_yet': 'No messages yet.',
      'buyer': 'Buyer',
      'classifieds_dashboard': 'Classifieds Dashboard',
      'items': 'items',
      'no_listings': 'No listings',
      'admin_dashboard': 'Admin Dashboard',
      'supabase_sql_setup': 'Supabase SQL Setup',
      'filter_options': 'Filter Options',
      'no_options_added_yet': 'No options added yet',
      'tap_plus_to_add': 'Tap + to add filter values',
      'add_option': 'Add Option',
      'category': 'Category',
      'type': 'Type',
      'edit_option': 'Edit Option',
      'this_option_will_be_removed': 'This option will be removed.',
      'inactive': 'Inactive',
      'table_not_found': 'Table not found. Run the SQL setup first.',
      'retry': 'Retry',
      'price_settings': 'Price Settings',
      'save_all_settings': 'Save All Settings',
      'settings_saved': 'Settings saved!',
      'regions_cities': 'Regions & Cities',
      'run_sql_setup_first': 'Run the SQL setup from Admin Dashboard first.',
      'no_regions_added_yet': 'No regions added yet',
      'tap_plus_to_add_region': 'Tap + to add a region',
      'add_region': 'Add Region',
      'edit_region': 'Edit Region',
      'active': 'Active',
      'delete_region': 'Delete Region?',
      'no_cities_added': 'No cities added',
      'manage_cities': 'Manage Cities',
      'no_cities_yet': 'No cities yet',
      'save_cities': 'Save Cities',
      // Sell/Listing
      'post_car_ad': 'Post Car Ad',
      'select_currency': 'Select Currency',
      'photos': 'Photos',
      'more': 'more',
      'post_mobile_ad': 'Post Mobile Ad',
      'post_property_ad': 'Post Property Ad',
      'add_field': 'Add field',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'search_failed': 'Search failed',
      // Categories
      'top_deals': 'Top Deals',
      'see_all': 'See All',
      'featured': 'Featured',
      'sort': 'Sort',
      'share': 'Share',
      'shared': 'Shared',
      'jobs': 'Jobs',
      'experience': 'Experience',
      'books_sports': 'Books & Sports',
      'no_jobs_found': 'No jobs found',
      'max_salary': 'Max Salary',
      'min_salary': 'Min Salary',
      'max_price': 'Max Price',
      'min_price': 'Min Price',
      // Detail screens
      'car_overview': 'Car Overview',
      'listing_not_found': 'Listing not found',
      'go_back': 'Go Back',
      'car_detail_not_available': 'Car detail screen requires additional setup',
      'property_detail_not_available': 'Property detail screen requires additional setup',
      'mobile_detail_not_available': 'Mobile detail screen requires additional setup',
      'electronics_detail_not_available': 'Electronics detail screen requires additional setup',
      'furniture_detail_not_available': 'Furniture detail screen requires additional setup',
      'jobs_detail_not_available': 'Jobs detail screen requires additional setup',
      'classifieds_detail_not_available': 'Classifieds detail screen requires additional setup',
      'spare_parts_detail_not_available': 'Spare parts detail screen requires additional setup',
      'detail_not_available': 'Detail screen not available for this category',
      'copied_text': 'Copied: {text}',
      'share_via_message': 'Share via Message',
      'link_copied': 'Link copied for {text}',
      'check_out_listing': 'Check out this car: {text} - {price} on Afghan Deals Pro',
    },
    'ps': {
      'Post for a customer': 'د پیرودونکي لپاره اعلان',
      'Customer Name': 'د پیرودونکي نوم',
      'Customer WhatsApp Number': 'د پیرودونکي د واټساپ شمېره',
      'The ad goes into the customer account for this number.': 'اعلان به د دې شمېرې د پیرودونکي حساب ته ولاړ شي.',
      'e.g. Ahmed Khan': 'لکه احمد خان',
      'WhatsApp Number': 'د واټساپ شمېره',
      'e.g. +93 70 123 4567': 'لکه +93 70 123 4567',
      'Enter the number with country code, e.g. +93 70 123 4567': 'شمېره د هېواد له کوډ سره ولیکئ، لکه +93 70 123 4567',
      'Add field': 'نوې برخه اضافه کړئ',
      'Camera': 'کیمره',
      'Gallery': 'ګالري',
      'Interior Color': 'دننی رنګ',
      'Regional Specs': 'د سیمې مشخصات',
      'Post Car Ad': 'د موټر اعلان',
      'Post Mobile Ad': 'د موبایل اعلان',
      'Describe your listing...': 'د خپل اعلان تشریح ولیکئ...',
      'Label (e.g. condition)': 'نوم (لکه حالت)',
      'Value (e.g. brand new)': 'ارزښت (لکه بالکل نوی)',
      'e.g.': 'لکه',
      'e.g. Dubai': 'لکه دوبی',
      'Country': 'هېواد',
      'Select Country': 'هېواد وټاکئ',
      'Select Currency': 'اسعار وټاکئ',
      'Select RAM': 'رام وټاکئ',
      'Select age': 'عمر وټاکئ',
      'Select battery health': 'د بټرۍ حالت وټاکئ',
      'Select body type': 'د بدنې ډول وټاکئ',
      'Select brand': 'برانډ وټاکئ',
      'Select color': 'رنګ وټاکئ',
      'Select furnishing': 'فرنیچر وټاکئ',
      'Select make': 'جوړونکی وټاکئ',
      'Select model': 'ماډل وټاکئ',
      'Select property type': 'د ملکیت ډول وټاکئ',
      'Select screen size': 'د سکرین کچه وټاکئ',
      'Select specs': 'مشخصات وټاکئ',
      'Select storage': 'حافظه وټاکئ',
      'Select warranty': 'ګرنټي وټاکئ',
      'Select year': 'کال وټاکئ',
      'White': 'سپین',
      'Silver': 'نقره یي',
      'Grey': 'خړ',
      'Black': 'تور',
      'Red': 'سور',
      'Gold': 'طلایي',
      'Orange': 'نارنجي',
      'Blue': 'نیلي',
      'Beige': 'کریمي',
      'Yellow': 'ژېړ',
      'Purple': 'بنفش',
      'Green': 'شنه',
      'Brown': 'نسواري',
      'Burgundy': 'تک سور',
      'Pink': 'ګلابي',
      'Other': 'بل',
      'Automatic': 'اتومات',
      'Manual': 'دستي',
      'Semi-Automatic': 'نیم اتومات',
      'Petrol': 'پټرول',
      'Diesel': 'ډیزل',
      'Hybrid': 'هایبرید',
      'Electric': 'بریښنایي',
      'Sedan': 'سیډان',
      'Pickup / Truck': 'پیکپ / لاری',
      'Hatchback': 'هچبک',
      'Van / Minivan': 'ون / مینی ون',
      'Coupe': 'کوپه',
      'Convertible': 'کنورټیبل',
      'Wagon': 'ویګن',
      'Crossover': 'کراس اوور',
      'New': 'نوی',
      'Used': 'کارول شوی',
      'Certified Pre-Owned': 'تصدیق شوی کارول شوی',
      'Brand New': 'بالکل نوی',
      'Refurbished': 'بیا جوړ شوی',
      'For Parts': 'د پرزو لپاره',
      'Individual': 'شخصي',
      'Dealer': 'ډیلر',
      'Showroom': 'شوروم',
      'For Sale': 'د پلور لپاره',
      'For Rent': 'د کرایې لپاره',
      'Apartment': 'اپارتمان',
      'House': 'کور',
      'Villa': 'ویلا',
      'Land': 'ځمکه',
      'Shop': 'دوکان',
      'Office': 'دفتر',
      'Studio': 'استودیو',
      'Furnished': 'فرنیچر لرونکی',
      'Semi Furnished': 'نیم فرنیچر لرونکی',
      'Unfurnished': 'بې فرنیچره',
      'Under Warranty': 'په ګرنټۍ کې',
      'No Warranty': 'بې ګرنټۍ',
      'GCC Specs': 'د خلیج مشخصات',
      'American Specs': 'امریکایي مشخصات',
      'European Specs': 'اروپایي مشخصات',
      'Canadian Specs': 'کاناډایي مشخصات',
      'Japanese Specs': 'جاپاني مشخصات',
      'Korean Specs': 'کوریایي مشخصات',
      '1 Month': 'یوه میاشت',
      '3 Months': 'درې میاشتې',
      '6 Months': 'شپږ میاشتې',
      '1 Year': 'یو کال',
      '2+ Years': '۲+ کاله',
      'Used Cars': 'کارول شوي موټرونه',
      'Rental Cars': 'کرایي موټرونه',
      'Afghanistan': 'افغانستان',
      'UAE': 'متحده عربي امارات',
      'KSA': 'سعودي عربستان',
      'Qatar': 'قطر',
      'Oman': 'عمان',
      'Syria': 'سوریه',
      'Kabul': 'کابل',
      'Kandahar': 'کندهار',
      'Herat': 'هرات',
      'Mazar-e-Sharif': 'مزار شریف',
      'Jalalabad': 'جلال آباد',
      'Kunduz': 'کندز',
      'Ghazni': 'غزني',
      'Khost': 'خوست',
      'Bamyan': 'بامیان',
      'Charikar': 'چاریکار',
      'Gardez': 'ګردېز',
      'Faizabad': 'فیض آباد',
      'Lashkar Gah': 'لښکرګاه',
      'Zaranj': 'زرنج',
      'Sheberghan': 'شبرغان',
      'Maimana': 'میمنه',
      'Taliqan': 'تالقان',
      'Aybak': 'ایبک',
      'Dubai': 'دوبی',
      'Abu Dhabi': 'ابوظبي',
      'Sharjah': 'شارجه',
      'Ajman': 'عجمان',
      'Al Ain': 'العین',
      'Fujairah': 'فجیره',
      'Ras Al Khaimah': 'راس الخیمه',
      'Umm Al Quwain': 'ام القیوین',
      'Riyadh': 'ریاض',
      'Jeddah': 'جده',
      'Mecca': 'مکه',
      'Medina': 'مدینه',
      'Dammam': 'دمام',
      'Khobar': 'خبر',
      'Abha': 'ابها',
      'Tabuk': 'تبوک',
      'Taif': 'طایف',
      'Qassim': 'قصیم',
      'Doha': 'دوحه',
      'Al Rayyan': 'الریان',
      'Al Wakrah': 'الوکره',
      'Al Khor': 'الخور',
      'Lusail': 'لوسیل',
      'Muscat': 'مسقط',
      'Salalah': 'صلاله',
      'Sohar': 'صحار',
      'Nizwa': 'نزوا',
      'Sur': 'صور',
      'Ibri': 'عبري',
      'Barka': 'برکا',
      'Damascus': 'دمشق',
      'Aleppo': 'حلب',
      'Homs': 'حمص',
      'Hama': 'حماه',
      'Latakia': 'لاذقیه',
      'Deir ez-Zor': 'دیرالزور',
      'account_restricted': 'ستاسو حساب ته د پیغام لېږلو اجازه بنده شوې ده.',
      'block': 'بلاک کول',
      'block_user_desc': 'تاسو کولی شئ دا کاروونکی اډمین ته راپور کړئ او خبرې اترې بندې پرېږدئ.',
      'blocked': 'بلاک شوی',
      'blocking': 'بلاکېږي...',
      'confirm_password': 'نوی پاسورډ تایید کړئ',
      'deactivate_account_desc': 'ستاسو حساب، اعلانونه او پروفایل به پټ شي. وروسته یې د ملاتړ یا اډمین له لارې بیا فعالولی شئ.',
      'delete_account_desc': 'دا به ستاسو حساب او ټول معلومات د تل لپاره ړنګ کړي. دا کار بیرته نه راګرځي.',
      'enter_email': 'خپل ایمیل ولیکئ',
      'fill_details_to_start': 'د پیل لپاره خپل معلومات ډک کړئ',
      'listings': 'اعلانونه',
      'location': 'ځای',
      'location_not_shared': 'ځای نه دی شریک شوی',
      'member_since': 'غړیتوب له',
      'message': 'پیغام ولیکئ...',
      'my_profile': 'زما پروفایل',
      'new_password': 'نوی پاسورډ',
      'not_shared': 'نه دی شریک شوی',
      'password_updated': 'پاسورډ په بریالیتوب سره بدل شو.',
      'passwords_not_match': 'پاسورډونه سره سمون نه خوري.',
      'phone': 'ټیلیفون',
      'report': 'راپور ورکول',
      'reporting': 'راپور لېږل کېږي...',
      'unblock_user_desc': 'دا کاروونکی به بیا درسره خبرې کولی شي.',
      'user_blocked_unblock_to_chat': 'دا کاروونکی بلاک دی. د خبرو اترو د دوام لپاره یې له پروفایل څخه بلاک لرې کړئ.',
      'user_profile': 'د کاروونکي پروفایل',
      'user_unblocked': 'د کاروونکي بلاک لرې شو.',
      'exterior_color': 'بهرنی رنګ',
      'interior_color': 'دننی رنګ',
      'regional_specs': 'د سیمې مشخصات',
      'seller_no_whatsapp': 'دې پلورونکي واټساپ شمېره نه ده ورکړې.',
      'whatsapp_not_installed': 'واټساپ ونه پرانیستل شو.',
      'home': 'کور',
      'chats': 'خبرې',
      'sell': 'پلورل',
      'my_ads': 'زما اعلانونه',
      'account': 'حساب',
      'profile': 'پروفایل',
      'account_settings': 'د حساب تنظیمات',
      'notifications': 'خبرتیاوې',
      'country': 'هېواد',
      'language': 'ژبه',
      'help_support': 'مرسته او ملاتړ',
      'choose_category': 'یوه کټګوري وټاکئ',
      'post_an_ad': 'اعلان خپور کړئ',
      'category_cars': 'موټرونه',
      'used_cars': 'کارېدلي موټرونه',
      'new_cars': 'نوي موټرونه',
      'export_cars': 'صادراتي موټرونه',
      'rental_cars': 'کرایي موټرونه',
      'new': 'نوی',
      'category_properties': 'ملکیتونه',
      'category_mobiles': 'موبایلونه',
      'category_spare_parts': 'پرزې',
      'category_electronics': 'برېښنايي/وسایل',
      'category_furniture': 'فرنیچر',
      'category_classifieds': 'متفرقه',
      'category_jobs': 'دندې',
      'category_coming_soon': 'د {category} سکرین به ژر فعال شي.',
      'find_listings': 'اعلانونه ومومئ',
      'find_listings_desc':
          'هېواد وټاکئ، کټګوري پرانیزئ، بیا د لټون، فلټر او ترتیب له لارې پایلې محدودې کړئ.',
      'post_ad': 'اعلان خپور کړئ',
      'post_ad_desc':
          'منځنی جمع تڼۍ ووهئ، کټګوري وټاکئ، معلومات ډک کړئ او د کتنې لپاره یې واستوئ.',
      'chat_with_sellers': 'له پلورونکو سره خبرې',
      'chat_with_sellers_desc':
          'اعلان پرانیزئ او Chat ووهئ. له چټ پروفایل څخه کاروونکي بلاک یا راپورولی شئ.',
      'call': 'زنګ',
      'email': 'ایمیل',
      'select_country': 'هېواد وټاکئ',
      'search': 'لټون',
      'discover': 'AFGHAN DEALS PRO کې اعلانونه ومومئ',
      'clear_all': 'ټول پاک کړئ',
      'apply': 'تطبیق',
      'filter': 'فلټر',
      'sort_by': 'ترتیب',
      'all': 'ټول',
      'latest': 'وروستی',
      'most_popular': 'تر ټولو مشهور',
      'popular': 'مشهور',
      'verified_sort': 'تایید شوی',
      'mobile_phones': 'موبایل تلیفونونه',
      'all_classifieds': 'ټول اعلانونه',
      'newest_to_oldest': 'له نوي تر زاړه',
      'oldest_to_newest': 'له زاړه تر نوي',
      'price_highest_to_lowest': 'بیه له لوړې نه ټیټې ته',
      'price_lowest_to_highest': 'بیه له ټیټې نه لوړې ته',
      'body_type': 'د بدن ډول',
      'year_range': 'د کال موده',
      'from': 'له',
      'to': 'تر',
      'results': 'پایلې',
      'search_cars': 'موټرونه ولټوئ...',
      'all_cars': 'ټول موټرونه',
      'add_listings_from_admin_dashboard': 'اعلانونه له اډمین ډشبورډ څخه اضافه کړئ',
      'makes': 'جوړوونکي',
      'models': 'ماډلونه',
      'sub_models': 'فرعي ماډلونه',
      'specs': 'مشخصات',
      'deal_type': 'د معاملې ډول',
      'ext_color': 'بهرنی رنګ',
      'driveline': 'ډرایو لاین',
      'cylinders': 'سلنډرونه',
      'int_color': 'داخلي رنګ',
      'region': 'سیمه',
      'price_range': 'د بیې موده',
      'max_price_aed': 'اعظمي بیه AED',
      'min_price_aed': 'اقل بیه AED',
      'chat': 'خبرې',
      'share_listing': 'اعلان شریک کړئ',
      'copy_to_clipboard': 'کاپي کړئ',
      'copy_link': 'لینک کاپي کړئ',
      'english': 'انګلیسي',
      'pashto': 'پښتو',
      'dari': 'دري',
      'urdu': 'اردو',
      'verified': 'تایید شوی',
      'get_verified': 'تایید ترلاسه کړئ',
      'joined_on': 'ګډون شوی په {date}',
      'guest': 'مېلمه',
      'log_out': 'وتل',
      'cancel': 'لغوه',
      'logout_confirm': 'ایا تاسو ډاډه یاست چې وتل غواړئ؟',
      'help': 'مرسته',
      'welcome_title': 'AFGHAN DEALS PRO ته ښه راغلاست',
      'welcome_subtitle': 'د پېرودونکو او پلورونکو باوري ټولنه',
      'continue_phone': 'د تلیفون سره دوام',
      'continue_google': 'د ګوګل سره دوام',
      'sign_in_apple': 'د Apple سره ننوتل',
      'or': 'یا',
      'login_email': 'د ایمیل سره ننوتل',
      'terms_intro': 'که تاسو دوام ورکوئ، نو تاسو منئ\n',
      'terms_text': 'د AFGHAN DEALS PRO شرطونه\nاو د محرمیت پالیسي',
      'sign_in': 'ننوتل',
      'sign_up': 'نوم لیکنه',
      'create_account': 'حساب جوړ کړئ',
      'password': 'پټنوم',
      'enter_password': 'خپل پټنوم دننه کړئ',
      'create_password': 'پټنوم جوړ کړئ (لږ تر لږه ۶ توري)',
      'dont_have_account': 'حساب نه لرئ؟ ',
      'already_have_account': 'حساب لرئ؟ ',
      'change_password': 'پټنوم بدل کړئ',
      'privacy': 'محرمیت',
      'blocked_users': 'بلاک شوي کاروونکي',
      'danger_zone': 'خطرناکه برخه',
      'deactivate_account': 'حساب غیر فعال کړئ',
      'delete_account': 'حساب حذف کړئ',
      'Basic Info': 'بنسټیز معلومات',
      'Ad Type': 'د اعلان ډول',
      'Ad Details': 'د اعلان معلومات',
      'Mobile Details': 'د موبایل معلومات',
      'Car Details': 'د موټر معلومات',
      'Property Details': 'د ملکیت معلومات',
      'Price': 'بیه',
      'Price & Location': 'بیه او ځای',
      'Location': 'ځای',
      'Contact & Amenities': 'اړیکه او اسانتیاوې',
      'Title': 'سرلیک',
      'Description': 'تفصیل',
      'Subcategory': 'فرعي کټګوري',
      'Property Type': 'د ملکیت ډول',
      'Purpose': 'هدف',
      'Furnishing': 'فرنیچر',
      'Bedrooms': 'د خوب خونې',
      'Bathrooms': 'تشنابونه',
      'Area (sqft)': 'مساحت (sqft)',
      'Seller Name': 'د پلورونکي نوم',
      'Phone': 'تلیفون',
      'Amenities (comma separated)': 'اسانتیاوې (په کامه جلا)',
      'Brand': 'برانډ',
      'Model': 'ماډل',
      'Condition': 'حالت',
      'Storage': 'ذخیره',
      'RAM': 'RAM',
      'Age': 'عمر',
      'Screen Size': 'د سکرین اندازه',
      'Color': 'رنګ',
      'Warranty': 'وارنټي',
      'Battery Health': 'د بیټرۍ حالت',
      'Version': 'نسخه',
      'Damage / Defects': 'زیان / عیبونه',
      'Seller Type': 'د پلورونکي ډول',
      'Rental Duration': 'د کرایې موده',
      'Make (Brand)': 'جوړونکی (برانډ)',
      'Year': 'کال',
      'Mileage (km)': 'مایلیج (km)',
      'Transmission': 'ګیربکس',
      'Fuel Type': 'د تېلو ډول',
      'Body Type': 'د باډي ډول',
      'Exterior Color': 'بهرنی رنګ',
      'Currency': 'اسعار',
      'City': 'ښار',
      'Address': 'پته',
      'Post Ad': 'اعلان خپور کړئ',
      'Photos': 'عکسونه',
      'Add Photo': 'عکس اضافه کړئ',
      'Cover': 'پوښ',
      'Choose from Gallery': 'له ګالري وټاکئ',
      'Take a Photo': 'عکس واخلئ',
      'First photo will be the cover. Tap + to add up to 10 photos.':
          'لومړی عکس به پوښ وي. تر ۱۰ عکسونو پورې اضافه کړئ.',
      // Common
      'no_listings_yet': 'اعلانونه نه شتل',
      'error': 'خرابي',
      'success': 'کامیابي',
      'loading': 'بار کېږي...',
      'delete': 'حذف',
      'save': 'ذخیره',
      'edit': 'سم کړئ',
      'add': 'اضافه کړئ',
      'done': 'سم',
      'yes': 'هو',
      'no': 'نه',
      'ok': 'سم دي',
      // Chat
      'say_hi_to_start': 'د خبرې د پیل لپاره سلام ووایې',
      'seen': 'لیدل شوي',
      'delete_chat': 'خبري حذف کړئ',
      'your_chat_is_empty': 'ستاسو خبري خالي دي!',
      'open_listing_and_tap_chat': 'اعلان پرانیزئ او Chat ووهئ خبري پیل کولو لپاره',
      'explore_listings': 'اعلانونه وگوره',
      'block_user': 'کاروونکي بلاک کړئ',
      'unblock_user': 'کاروونکي آزاد کړئ',
      'user_blocked_chat_disabled': 'کاروونکي بلاک شوی. خبري غیر فعال دي.',
      'user_unblocked_chat_enabled': 'کاروونکي آزاد شوی. خبري فعال دي.',
      'report_user': 'کاروونکي راپورت کړئ',
      'report_submitted': 'راپورت اداره ته واستول شو.',
      'chat_listing': 'د خبرو اعلان',
      // Profile
      'profile_name': 'پروفایل نوم',
      'displayed_on_profile': 'دا تاسو د پروفایل کې ښودل کيږي',
      'account_details': 'د حساب تفصیلات',
      'not_visible_to_others': 'دا د نورو لپاره نه لیدل کيږي',
      'save_changes': 'بدلون ذخیره کړئ',
      'profile_saved_successfully': 'پروفایل کامیابي سره ذخیره شو!',
      'failed_to_save': 'ذخیره کول ناکام شو',
      'first_name': 'لومړی نوم',
      'last_name': 'کورنی نوم',
      'date_of_birth': 'د زیږون نیته',
      'select_date_of_birth': 'د زیږون نیته وټاکئ',
      'nationality': 'تابعیت',
      'select_nationality': 'تابعیت وټاکئ',
      'gender': 'جنس',
      'select_gender': 'جنس وټاکئ',
      'male': 'نر',
      'female': 'ښځه',
      'prefer_not_to_say': 'د ويلو لپاره غوره نه کوم',
      'update_password': 'پټنوم تازه کړئ',
      'deactivate': 'غیر فعال کړئ',
      'delete_account_confirm': 'حساب حذف کړئ',
      'blocked_users_list': 'بلاک شوي کاروونکي',
      'no_blocked_users': 'بلاک شوي کاروونکي نشتل',
      'unblock': 'آزاد کړئ',
      'push_notifications': 'د فشار اطلاعات',
      'enable_all_notifications': 'ټولو د فشار اطلاعات فعال کړئ',
      'upload_failed': 'اپ لوډ ناکام شو',
      // Auth
      'full_name': 'مکمل نوم',
      'enter_full_name': 'خپل مکمل نوم دننه کړئ',
      'name_required': 'نوم ضروري دي',
      'email_required': 'ای میل ضروري دي',
      'valid_email_required': 'صحيح ای میل دننه کړئ',
      'phone_number': 'تلیفون نمبر',
      'eg_phone': 'مثال +93700000000',
      'password_required': 'پټنوم ضروري دي',
      'min_6_characters': 'لږ تر لږه ۶ توري',
      'select_country_code': 'هېواد کوډ وټاکئ',
      'send_code': 'کوډ واستوئ',
      'enter_verification_code': 'د تصدیق کوډ دننه کړئ',
      'submit': 'واستوئ',
      'welcome_back': 'بیا ښه راغلاست',
      'sign_in_to_account': 'خپل حساب ته ننوتل',
      'afghanistan': 'افغانستان',
      'pakistan': 'پاکستان',
      'iran': 'ایران',
      'india': 'هندوستان',
      'bangladesh': 'بنگله دیش',
      'turkey': 'ترکیه',
      'saudi_arabia': 'سعودی عربستان',
      'oman': 'عمان',
      'qatar': 'قطر',
      'ksa': 'سعودي عرب',
      'syria': 'سوریه',
      'uae_short': 'امارات',
      'uae': 'متحده امارات',
      'usa': 'متحده ایالات',
      'uk': 'برطانیه',
      'china': 'چین',
      'russia': 'روسیه',
      'germany': 'آلمان',
      'france': 'فرانسه',
      'canada': 'کاناډا',
      'australia': 'آسترالیا',
      'japan': 'جاپان',
      'korea': 'جنوبی کوریا',
      'malaysia': 'مالزیا',
      'indonesia': 'اندونیزیا',
      'egypt': 'مصر',
      'nigeria': 'نیجریا',
      'kenya': 'کنیا',
      'south_africa': 'جنوبی افریقا',
      'other': 'نور',
      // Admin
      'all_chats': 'ټولې خبري',
      'access_denied': 'د رسي مسدود',
      'no_chats_yet': 'خبري نشتل.',
      'no_messages_yet': 'پیغامونه نشتل.',
      'buyer': 'پیرونکی',
      'classifieds_dashboard': 'د طبقه بندي ډیشبورډ',
      'items': 'توکي',
      'no_listings': 'اعلانونه نشتل',
      'admin_dashboard': 'د اداری ډیشبورډ',
      'supabase_sql_setup': 'Supabase SQL تنظیم',
      'filter_options': 'د فلټر انتخابات',
      'no_options_added_yet': 'انتخابات اضافه نه شوي',
      'tap_plus_to_add': 'د فلټر ارزښتونو اضافه کولو لپاره + ووهئ',
      'add_option': 'انتخاب اضافه کړئ',
      'category': 'کټګوري',
      'type': 'ډول',
      'edit_option': 'انتخاب سم کړئ',
      'this_option_will_be_removed': 'دا انتخاب لیري کېدونکی دی.',
      'inactive': 'غیر فعال',
      'table_not_found': 'جدول نه وموندل شو. SQL تنظیم پرانیزئ.',
      'retry': 'دوبارې کوشش کړئ',
      'price_settings': 'د بیې تنظیمات',
      'save_all_settings': 'ټولې تنظیمات ذخیره کړئ',
      'settings_saved': 'تنظیمات ذخیره شول!',
      'regions_cities': 'سیمې او ښارونه',
      'run_sql_setup_first': 'مخکې د اداری ډیشبورډ څخه SQL تنظیم پرانیزئ.',
      'no_regions_added_yet': 'سیمې اضافه نه شوي',
      'tap_plus_to_add_region': 'سیمه اضافه کولو لپاره + ووهئ',
      'add_region': 'سیمه اضافه کړئ',
      'edit_region': 'سیمه سم کړئ',
      'active': 'فعال',
      'delete_region': 'سیمه حذف کړئ؟',
      'no_cities_added': 'ښارونه اضافه نه شوي',
      'manage_cities': 'ښارونه سمبالئ',
      'no_cities_yet': 'ښارونه نه شتل',
      'save_cities': 'ښارونه ذخیره کړئ',
      // Sell/Listing
      'post_car_ad': 'د موټر اعلان خپور کړئ',
      'select_currency': 'اسعار وټاکئ',
      'photos': 'عکسونه',
      'more': 'نور',
      'post_mobile_ad': 'د موبایل اعلان خپور کړئ',
      'post_property_ad': 'د ملکیت اعلان خپور کړئ',
      'add_field': 'ساحه اضافه کړئ',
      'gallery': 'ګالري',
      'camera': 'دوربين',
      'search_failed': 'لټون ناکام شو',
      // Categories
      'top_deals': 'غوره معاملې',
      'see_all': 'ټول وگوره',
      'featured': 'خصوصي',
      'sort': 'ترتیب',
      'share': 'شریک کړئ',
      'shared': 'شریک شوی',
      'jobs': 'کاروبار',
      'experience': 'تجربه',
      'books_sports': 'کتابونه او ورزش',
      'no_jobs_found': 'کاروبار نه وموندل شو',
      'max_salary': 'زیاتره معاش',
      'min_salary': 'کمتره معاش',
      'max_price': 'زیاتره بیه',
      'min_price': 'کمتره بیه',
      // Detail screens
      'car_overview': 'د موتر جائزه',
      'listing_not_found': 'اعلان نه وموندل شو',
      'go_back': 'پرت شئ',
      'car_detail_not_available': 'د موتر تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'property_detail_not_available': 'د ملکیت تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'mobile_detail_not_available': 'د موبایل تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'electronics_detail_not_available': 'د الیکٹرانکی تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'furniture_detail_not_available': 'د فرنیچر تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'jobs_detail_not_available': 'د کاروبار تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'classifieds_detail_not_available': 'د تقسیم شوو تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'spare_parts_detail_not_available': 'د تیټې برخې تفصیل سکرین اضافي سیٹ اپ ته ضرورت دی',
      'detail_not_available': 'د تفصیل سکرین د دې کټګوري لپاره دستیاب نه دی',
      'copied_text': 'کاپي شو: {text}',
      'share_via_message': 'د پیغام سره شریک کړئ',
      'link_copied': 'لینک کاپي شو د {text}',
      'check_out_listing': 'دا موتر وگوره: {text} - {price} د Afghan Deals Pro کې',
    },
    'fa': {
      'Post for a customer': 'ثبت اعلان برای مشتری',
      'Customer Name': 'نام مشتری',
      'Customer WhatsApp Number': 'شماره واتساپ مشتری',
      'The ad goes into the customer account for this number.': 'اعلان به حساب مشتری این شماره می‌رود.',
      'e.g. Ahmed Khan': 'مثلاً احمد خان',
      'exterior_color': 'رنگ بیرونی',
      'interior_color': 'رنگ داخلی',
      'regional_specs': 'مشخصات منطقه‌ای',
      'seller_no_whatsapp': 'این فروشنده شماره واتساپ اضافه نکرده است.',
      'whatsapp_not_installed': 'واتساپ باز نشد.',
      'home': 'خانه',
      'chats': 'چت‌ها',
      'sell': 'فروش',
      'my_ads': 'اعلان‌های من',
      'account': 'حساب',
      'profile': 'پروفایل',
      'account_settings': 'تنظیمات حساب',
      'notifications': 'اعلان‌ها',
      'country': 'کشور',
      'language': 'زبان',
      'help_support': 'کمک و پشتیبانی',
      'choose_category': 'یک دسته‌بندی را انتخاب کنید',
      'post_an_ad': 'آگهی ثبت کنید',
      'category_cars': 'موترها',
      'used_cars': 'موترهای کارکرده',
      'new_cars': 'موترهای نو',
      'export_cars': 'موترهای صادراتی',
      'rental_cars': 'موترهای کرایی',
      'new': 'جدید',
      'category_properties': 'املاک',
      'category_mobiles': 'موبایل‌ها',
      'category_spare_parts': 'پرچه‌جات',
      'category_electronics': 'الکترونیک/وسایل',
      'category_furniture': 'مبل',
      'category_classifieds': 'سایر آگهی‌ها',
      'category_jobs': 'کارها',
      'category_coming_soon': 'صفحه {category} به‌زودی فعال می‌شود.',
      'find_listings': 'یافتن اعلان‌ها',
      'find_listings_desc':
          'کشور را انتخاب کنید، یک دسته را باز کنید، سپس با جستجو، فیلتر و ترتیب نتایج را محدود کنید.',
      'post_ad': 'ثبت اعلان',
      'post_ad_desc':
          'دکمه جمع وسط را بزنید، دسته را انتخاب کنید، جزئیات را وارد کنید و برای بررسی ارسال کنید.',
      'chat_with_sellers': 'چت با فروشندگان',
      'chat_with_sellers_desc':
          'اعلان را باز کنید و Chat را بزنید. از پروفایل چت می‌توانید کاربر را بلاک یا گزارش کنید.',
      'call': 'تماس',
      'email': 'ایمیل',
      'select_country': 'انتخاب کشور',
      'search': 'جستجو',
      'discover': 'اعلان‌ها را در AFGHAN DEALS PRO پیدا کنید',
      'clear_all': 'پاک کردن همه',
      'apply': 'اعمال',
      'filter': 'فیلتر',
      'sort_by': 'ترتیب',
      'all': 'همه',
      'latest': 'جدیدترین',
      'most_popular': 'محبوب‌ترین',
      'popular': 'محبوب',
      'verified_sort': 'تأیید شده',
      'mobile_phones': 'موبایل‌ها',
      'all_classifieds': 'همه اعلانات',
      'newest_to_oldest': 'از جدید به قدیم',
      'oldest_to_newest': 'از قدیم به جدید',
      'price_highest_to_lowest': 'قیمت از زیاد به کم',
      'price_lowest_to_highest': 'قیمت از کم به زیاد',
      'body_type': 'نوع بدنه',
      'year_range': 'بازه سال',
      'from': 'از',
      'to': 'تا',
      'results': 'نتیجه',
      'search_cars': 'جستجوی موترها...',
      'all_cars': 'همه موترها',
      'add_listings_from_admin_dashboard': 'آگهی‌ها را از داشبورد ادمین اضافه کنید',
      'makes': 'سازنده‌ها',
      'models': 'مدل‌ها',
      'sub_models': 'زیرمدل‌ها',
      'specs': 'مشخصات',
      'deal_type': 'نوع معامله',
      'ext_color': 'رنگ بیرونی',
      'driveline': 'سیستم انتقال',
      'cylinders': 'سیلندرها',
      'int_color': 'رنگ داخلی',
      'region': 'منطقه',
      'price_range': 'بازه قیمت',
      'max_price_aed': 'حداکثر قیمت AED',
      'min_price_aed': 'حداقل قیمت AED',
      'chat': 'چت',
      'share_listing': 'اشتراک اعلان',
      'copy_to_clipboard': 'کپی در کلیپ‌بورد',
      'copy_link': 'کپی لینک',
      'english': 'انگلیسی',
      'pashto': 'پشتو',
      'dari': 'دری',
      'urdu': 'اردو',
      'verified': 'تایید شده',
      'get_verified': 'تایید شوید',
      'joined_on': 'عضویت در {date}',
      'guest': 'مهمان',
      'log_out': 'خروج',
      'cancel': 'لغو',
      'logout_confirm': 'آیا مطمئن هستید که می‌خواهید خارج شوید؟',
      'help': 'کمک',
      'welcome_title': 'به AFGHAN DEALS PRO خوش آمدید',
      'welcome_subtitle': 'جامعه قابل اعتماد خریداران و فروشندگان',
      'continue_phone': 'ادامه با تلفن',
      'continue_google': 'ادامه با گوگل',
      'sign_in_apple': 'ورود با Apple',
      'or': 'یا',
      'login_email': 'ورود با ایمیل',
      'terms_intro': 'اگر ادامه دهید، شما می‌پذیرید\n',
      'terms_text': 'شرایط و قوانین AFGHAN DEALS PRO\nو سیاست حریم خصوصی',
      'sign_in': 'ورود',
      'sign_up': 'ثبت نام',
      'create_account': 'ایجاد حساب',
      'password': 'رمز عبور',
      'enter_password': 'رمز عبور خود را وارد کنید',
      'create_password': 'رمز عبور بسازید (حداقل ۶ حرف)',
      'dont_have_account': 'حساب ندارید؟ ',
      'already_have_account': 'حساب دارید؟ ',
      'change_password': 'تغییر رمز عبور',
      'privacy': 'حریم خصوصی',
      'blocked_users': 'کاربران بلاک شده',
      'danger_zone': 'بخش حساس',
      'deactivate_account': 'غیرفعال کردن حساب',
      'delete_account': 'حذف حساب',
      'Basic Info': 'اطلاعات پایه',
      'Ad Type': 'نوع اعلان',
      'Ad Details': 'جزئیات اعلان',
      'Mobile Details': 'جزئیات موبایل',
      'Car Details': 'جزئیات موتر',
      'Property Details': 'جزئیات ملکیت',
      'Price': 'قیمت',
      'Price & Location': 'قیمت و موقعیت',
      'Location': 'موقعیت',
      'Contact & Amenities': 'تماس و امکانات',
      'Title': 'عنوان',
      'Description': 'توضیحات',
      'Subcategory': 'زیر دسته',
      'Property Type': 'نوع ملکیت',
      'Purpose': 'هدف',
      'Furnishing': 'فرنیچر',
      'Bedrooms': 'اتاق خواب',
      'Bathrooms': 'حمام',
      'Area (sqft)': 'مساحت (sqft)',
      'Seller Name': 'نام فروشنده',
      'Phone': 'تلفن',
      'Amenities (comma separated)': 'امکانات (جدا با کامه)',
      'Brand': 'برند',
      'Model': 'مدل',
      'Condition': 'وضعیت',
      'Storage': 'ذخیره',
      'RAM': 'RAM',
      'Age': 'عمر',
      'Screen Size': 'اندازه صفحه',
      'Color': 'رنگ',
      'Warranty': 'گارانتی',
      'Battery Health': 'سلامت باتری',
      'Version': 'نسخه',
      'Damage / Defects': 'خرابی / نقص',
      'Seller Type': 'نوع فروشنده',
      'Rental Duration': 'مدت کرایه',
      'Make (Brand)': 'سازنده (برند)',
      'Year': 'سال',
      'Mileage (km)': 'کارکرد (km)',
      'Transmission': 'گیربکس',
      'Fuel Type': 'نوع سوخت',
      'Body Type': 'نوع بدنه',
      'Exterior Color': 'رنگ بیرونی',
      'Currency': 'واحد پول',
      'City': 'شهر',
      'Address': 'آدرس',
      'Post Ad': 'ثبت اعلان',
      'Photos': 'عکس‌ها',
      'Add Photo': 'افزودن عکس',
      'Cover': 'کاور',
      'Choose from Gallery': 'انتخاب از گالری',
      'Take a Photo': 'گرفتن عکس',
      'First photo will be the cover. Tap + to add up to 10 photos.':
          'اولین عکس کاور خواهد بود. تا ۱۰ عکس اضافه کنید.',
      // Common
      'no_listings_yet': 'هیچ اعلان نیست',
      'error': 'خطا',
      'success': 'موفق',
      'loading': 'در حال بارگزاری...',
      'delete': 'حذف',
      'save': 'ذخیره',
      'edit': 'ویرایش',
      'add': 'اضافه کنید',
      'done': 'تمام',
      'yes': 'بلی',
      'no': 'خیر',
      'ok': 'تایید',
      // Chat
      'say_hi_to_start': 'سلام برای شروع چت بگویید',
      'seen': 'دیده شد',
      'delete_chat': 'حذف چت',
      'your_chat_is_empty': 'چت شما خالی است!',
      'open_listing_and_tap_chat': 'اعلان را باز کنید و Chat را بزنید تا شروع کنید',
      'explore_listings': 'کاوش اعلانات',
      'block_user': 'کاربر را بلاک کنید',
      'unblock_user': 'کاربر را آزاد کنید',
      'user_blocked_chat_disabled': 'کاربر بلاک شده است. چت غیرفعال است.',
      'user_unblocked_chat_enabled': 'کاربر آزاد شده است. چت فعال است.',
      'report_user': 'کاربر را گزارش کنید',
      'report_submitted': 'گزارش به ادمین ارسال شد.',
      'chat_listing': 'اعلان چت',
      // Profile
      'profile_name': 'نام پروفایل',
      'displayed_on_profile': 'این در پروفایل شما نمایش داده می‌شود',
      'account_details': 'جزئیات حساب',
      'not_visible_to_others': 'این برای سایرین نمایان نیست',
      'save_changes': 'ذخیره تغییرات',
      'profile_saved_successfully': 'پروفایل با موفقیت ذخیره شد!',
      'failed_to_save': 'ذخیره ناموفق بود',
      'first_name': 'نام',
      'last_name': 'نام خانوادگی',
      'date_of_birth': 'تاریخ تولد',
      'select_date_of_birth': 'تاریخ تولد را انتخاب کنید',
      'nationality': 'ملیت',
      'select_nationality': 'ملیت را انتخاب کنید',
      'gender': 'جنسیت',
      'select_gender': 'جنسیت را انتخاب کنید',
      'male': 'مرد',
      'female': 'زن',
      'prefer_not_to_say': 'ترجیح می‌دهم نگویم',
      'update_password': 'بروزرسانی رمز عبور',
      'deactivate': 'غیرفعال کنید',
      'delete_account_confirm': 'حذف حساب',
      'blocked_users_list': 'کاربران بلاک شده',
      'no_blocked_users': 'کاربران بلاک شده نیستند',
      'unblock': 'آزاد کنید',
      'push_notifications': 'اطلاعیه های فشاری',
      'enable_all_notifications': 'تمام اطلاعات فشاری را فعال کنید',
      'upload_failed': 'بارگذاری ناموفق بود',
      // Auth
      'full_name': 'نام کامل',
      'enter_full_name': 'نام کامل خود را وارد کنید',
      'name_required': 'نام الزامی است',
      'email_required': 'ایمیل الزامی است',
      'valid_email_required': 'یک ایمیل معتبر وارد کنید',
      'phone_number': 'شماره تماس',
      'eg_phone': 'مثال +93700000000',
      'password_required': 'رمز عبور الزامی است',
      'min_6_characters': 'حداقل ۶ حرف',
      'select_country_code': 'کد کشور را انتخاب کنید',
      'send_code': 'کد ارسال کنید',
      'enter_verification_code': 'کد تایید را وارد کنید',
      'submit': 'ارسال',
      'welcome_back': 'خوش آمدید',
      'sign_in_to_account': 'وارد حساب خود شوید',
      'afghanistan': 'افغانستان',
      'pakistan': 'پاکستان',
      'iran': 'ایران',
      'india': 'هند',
      'bangladesh': 'بنگلادش',
      'turkey': 'ترکیه',
      'saudi_arabia': 'عربستان سعودی',
      'oman': 'عمان',
      'qatar': 'قطر',
      'ksa': 'عربستان سعودی',
      'syria': 'سوریه',
      'uae_short': 'امارات',
      'uae': 'امارات متحده',
      'usa': 'ایالات متحده',
      'uk': 'انگلستان',
      'china': 'چین',
      'russia': 'روسیه',
      'germany': 'آلمان',
      'france': 'فرانسه',
      'canada': 'کانادا',
      'australia': 'استرالیا',
      'japan': 'ژاپن',
      'korea': 'کره جنوبی',
      'malaysia': 'مالزی',
      'indonesia': 'اندونزی',
      'egypt': 'مصر',
      'nigeria': 'نیجریه',
      'kenya': 'کنیا',
      'south_africa': 'آفریقای جنوبی',
      'other': 'دیگر',
      // Admin
      'all_chats': 'تمام چت‌ها',
      'access_denied': 'دسترسی رد شد',
      'no_chats_yet': 'هنوز چتی نیست.',
      'no_messages_yet': 'هنوز پیامی نیست.',
      'buyer': 'خریدار',
      'classifieds_dashboard': 'داشبورد طبقه‌بندی‌ها',
      'items': 'اشیاء',
      'no_listings': 'اعلانی نیست',
      'admin_dashboard': 'داشبورد مدیر',
      'supabase_sql_setup': 'راه‌اندازی Supabase SQL',
      'filter_options': 'گزینه‌های فیلتر',
      'no_options_added_yet': 'هنوز گزینه‌ای اضافه نشده',
      'tap_plus_to_add': 'برای اضافه کردن مقادیر فیلتر ضربه بزنید',
      'add_option': 'اضافه کردن گزینه',
      'category': 'دسته',
      'type': 'نوع',
      'edit_option': 'ویرایش گزینه',
      'this_option_will_be_removed': 'این گزینه حذف خواهد شد.',
      'inactive': 'غیرفعال',
      'table_not_found': 'جدول یافت نشد. ابتدا راه‌اندازی SQL را اجرا کنید.',
      'retry': 'دوباره سعی کنید',
      'price_settings': 'تنظیمات قیمت',
      'save_all_settings': 'ذخیره تمام تنظیمات',
      'settings_saved': 'تنظیمات ذخیره شد!',
      'regions_cities': 'مناطق و شهرها',
      'run_sql_setup_first': 'ابتدا راه‌اندازی SQL را از داشبورد مدیر اجرا کنید.',
      'no_regions_added_yet': 'هنوز منطقه‌ای اضافه نشده',
      'tap_plus_to_add_region': 'برای اضافه کردن منطقه ضربه بزنید',
      'add_region': 'اضافه کردن منطقه',
      'edit_region': 'ویرایش منطقه',
      'active': 'فعال',
      'delete_region': 'حذف منطقه؟',
      'no_cities_added': 'شهری اضافه نشده',
      'manage_cities': 'مدیریت شهرها',
      'no_cities_yet': 'هنوز شهری نیست',
      'save_cities': 'ذخیره شهرها',
      // Sell/Listing
      'post_car_ad': 'ثبت اعلان خودرو',
      'select_currency': 'انتخاب واحد پول',
      'photos': 'عکس‌ها',
      'more': 'بیشتر',
      'post_mobile_ad': 'ثبت اعلان موبایل',
      'post_property_ad': 'ثبت اعلان ملک',
      'add_field': 'اضافه کردن فیلد',
      'gallery': 'گالری',
      'camera': 'دوربین',
      'search_failed': 'جستجو ناموفق بود',
      // Categories
      'top_deals': 'بهترین پیشنهادات',
      'see_all': 'مشاهده همه',
      'featured': 'ویژه',
      'sort': 'مرتب‌سازی',
      'share': 'اشتراک',
      'shared': 'اشتراک شد',
      'jobs': 'شغل‌ها',
      'experience': 'تجربه',
      'books_sports': 'کتاب و ورزش',
      'no_jobs_found': 'شغلی یافت نشد',
      'max_salary': 'حداکثر حقوق',
      'min_salary': 'حداقل حقوق',
      'max_price': 'حداکثر قیمت',
      'min_price': 'حداقل قیمت',
      // Detail screens
      'car_overview': 'مروری ماشین',
      'listing_not_found': 'فہرست پیدا نشد',
      'go_back': 'برگشت',
      'car_detail_not_available': 'صفحہ جزئیات خودرو نیاز دارد تنظیم اضافی',
      'property_detail_not_available': 'صفحہ جزئیات ملکیت نیاز دارد تنظیم اضافی',
      'mobile_detail_not_available': 'صفحہ جزئیات موبائل نیاز دارد تنظیم اضافی',
      'electronics_detail_not_available': 'صفحہ جزئیات الیکٹرانکس نیاز دارد تنظیم اضافی',
      'furniture_detail_not_available': 'صفحہ جزئیات فرنیچر نیاز دارد تنظیم اضافی',
      'jobs_detail_not_available': 'صفحہ جزئیات ملازمت نیاز دارد تنظیم اضافی',
      'classifieds_detail_not_available': 'صفحہ جزئیات درجہ بندی نیاز دارد تنظیم اضافی',
      'spare_parts_detail_not_available': 'صفحہ جزئیات حصے نیاز دارد تنظیم اضافی',
      'detail_not_available': 'صفحہ جزئیات اس زمرہ کے لیے دستیاب نہیں ہے',
      'copied_text': 'نقل: {text}',
      'share_via_message': 'پیغام کے ذریعے شیئر کریں',
      'link_copied': 'لنک نقل {text}',
      'check_out_listing': 'اس خودرو کو دیکھیں: {text} - {price} on Afghan Deals Pro',
    },
    'ur': {
      'Post for a customer': 'گاہک کے لیے اشتہار',
      'Customer Name': 'گاہک کا نام',
      'Customer WhatsApp Number': 'گاہک کا واٹس ایپ نمبر',
      'The ad goes into the customer account for this number.': 'اشتہار اس نمبر کے گاہک کے اکاؤنٹ میں جائے گا۔',
      'e.g. Ahmed Khan': 'مثلاً احمد خان',
      'exterior_color': 'بیرونی رنگ',
      'interior_color': 'اندرونی رنگ',
      'regional_specs': 'علاقائی تفصیلات',
      'seller_no_whatsapp': 'اس بیچنے والے نے واٹس ایپ نمبر شامل نہیں کیا۔',
      'whatsapp_not_installed': 'واٹس ایپ نہیں کھل سکا۔',
      'home': 'ہوم',
      'chats': 'چیٹس',
      'sell': 'سیل',
      'my_ads': 'میرے اشتہار',
      'account': 'اکاؤنٹ',
      'profile': 'پروفائل',
      'account_settings': 'اکاؤنٹ سیٹنگز',
      'notifications': 'نوٹیفکیشنز',
      'country': 'ملک',
      'language': 'زبان',
      'help_support': 'مدد اور سپورٹ',
      'choose_category': 'ایک کیٹیگری منتخب کریں',
      'post_an_ad': 'اشتہار پوسٹ کریں',
      'category_cars': 'گاڑیاں',
      'used_cars': 'استعمال شدہ کاریں',
      'new_cars': 'نئی کاریں',
      'export_cars': 'ایکسپورٹ کاریں',
      'rental_cars': 'کرائے کی کاریں',
      'new': 'نیا',
      'category_properties': 'پراپرٹی',
      'category_mobiles': 'موبائلز',
      'category_spare_parts': 'اسپیئر پارٹس',
      'category_electronics': 'الیکٹرانکس/اپلائنسز',
      'category_furniture': 'فرنیچر',
      'category_classifieds': 'کلاسیفائیڈز',
      'category_jobs': 'نوکریاں',
      'category_coming_soon': '{category} کیٹیگری کی سکرین جلد فعال ہو گی۔',
      'find_listings': 'لسٹنگز تلاش کریں',
      'find_listings_desc':
          'ملک منتخب کریں، کیٹیگری کھولیں، پھر سرچ، فلٹر اور سارٹ سے نتائج کم کریں۔',
      'post_ad': 'اشتہار پوسٹ کریں',
      'post_ad_desc':
          'درمیان والا پلس بٹن دبائیں، کیٹیگری منتخب کریں، تفصیلات بھریں اور ریویو کے لیے بھیجیں۔',
      'chat_with_sellers': 'سیلرز سے چیٹ',
      'chat_with_sellers_desc':
          'لسٹنگ کھولیں اور Chat دبائیں۔ چیٹ پروفائل سے صارف کو بلاک یا رپورٹ کر سکتے ہیں۔',
      'call': 'کال',
      'email': 'ای میل',
      'select_country': 'ملک منتخب کریں',
      'search': 'تلاش',
      'discover': 'AFGHAN DEALS PRO پر ڈیلز تلاش کریں',
      'clear_all': 'سب صاف کریں',
      'apply': 'لاگو کریں',
      'filter': 'فلٹر',
      'sort_by': 'ترتیب',
      'all': 'سب',
      'latest': 'تازہ ترین',
      'most_popular': 'سب سے مقبول',
      'popular': 'مقبول',
      'verified_sort': 'تصدیق شدہ',
      'mobile_phones': 'موبائل فونز',
      'all_classifieds': 'تمام کلاسیفائیڈز',
      'newest_to_oldest': 'نئے سے پرانے',
      'oldest_to_newest': 'پرانے سے نئے',
      'price_highest_to_lowest': 'قیمت زیادہ سے کم',
      'price_lowest_to_highest': 'قیمت کم سے زیادہ',
      'body_type': 'باڈی ٹائپ',
      'year_range': 'سال کی حد',
      'from': 'سے',
      'to': 'تک',
      'results': 'نتائج',
      'search_cars': 'کاریں تلاش کریں...',
      'all_cars': 'تمام کاریں',
      'add_listings_from_admin_dashboard': 'ایڈمن ڈیش بورڈ سے لسٹنگ شامل کریں',
      'makes': 'برانڈز',
      'models': 'ماڈلز',
      'sub_models': 'ذیلی ماڈلز',
      'specs': 'تفصیلات',
      'deal_type': 'ڈیل کی قسم',
      'ext_color': 'بیرونی رنگ',
      'driveline': 'ڈرائیو لائن',
      'cylinders': 'سلنڈرز',
      'int_color': 'اندرونی رنگ',
      'region': 'علاقہ',
      'price_range': 'قیمت کی حد',
      'max_price_aed': 'زیادہ سے زیادہ قیمت AED',
      'min_price_aed': 'کم از کم قیمت AED',
      'chat': 'چیٹ',
      'share_listing': 'لسٹنگ شیئر کریں',
      'copy_to_clipboard': 'کاپی کریں',
      'copy_link': 'لنک کاپی کریں',
      'english': 'انگریزی',
      'pashto': 'پشتو',
      'dari': 'دری',
      'urdu': 'اردو',
      'verified': 'تصدیق شدہ',
      'get_verified': 'تصدیق حاصل کریں',
      'joined_on': '{date} کو شامل ہوئے',
      'guest': 'مہمان',
      'log_out': 'لاگ آؤٹ',
      'cancel': 'منسوخ',
      'logout_confirm': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
      'help': 'مدد',
      'welcome_title': 'AFGHAN DEALS PRO میں خوش آمدید',
      'welcome_subtitle': 'خریداروں اور فروخت کنندگان کی قابل اعتماد کمیونٹی',
      'continue_phone': 'فون کے ساتھ جاری رکھیں',
      'continue_google': 'گوگل کے ساتھ جاری رکھیں',
      'sign_in_apple': 'Apple کے ساتھ سائن ان',
      'or': 'یا',
      'login_email': 'ای میل سے لاگ ان',
      'terms_intro': 'اگر آپ جاری رکھتے ہیں تو آپ قبول کرتے ہیں\n',
      'terms_text': 'AFGHAN DEALS PRO کی شرائط\nاور پرائیویسی پالیسی',
      'sign_in': 'سائن ان',
      'sign_up': 'سائن اپ',
      'create_account': 'اکاؤنٹ بنائیں',
      'password': 'پاس ورڈ',
      'enter_password': 'اپنا پاس ورڈ درج کریں',
      'create_password': 'پاس ورڈ بنائیں (کم از کم 6 حروف)',
      'dont_have_account': 'اکاؤنٹ نہیں ہے؟ ',
      'already_have_account': 'پہلے سے اکاؤنٹ ہے؟ ',
      'change_password': 'پاس ورڈ تبدیل کریں',
      'privacy': 'پرائیویسی',
      'blocked_users': 'بلاکڈ صارفین',
      'danger_zone': 'خطرے کا حصہ',
      'deactivate_account': 'اکاؤنٹ غیر فعال کریں',
      'delete_account': 'اکاؤنٹ حذف کریں',
      'Basic Info': 'بنیادی معلومات',
      'Ad Type': 'اشتہار کی قسم',
      'Ad Details': 'اشتہار کی تفصیلات',
      'Mobile Details': 'موبائل کی تفصیلات',
      'Car Details': 'گاڑی کی تفصیلات',
      'Property Details': 'پراپرٹی کی تفصیلات',
      'Price': 'قیمت',
      'Price & Location': 'قیمت اور مقام',
      'Location': 'مقام',
      'Contact & Amenities': 'رابطہ اور سہولیات',
      'Title': 'عنوان',
      'Description': 'تفصیل',
      'Subcategory': 'ذیلی کیٹیگری',
      'Property Type': 'پراپرٹی کی قسم',
      'Purpose': 'مقصد',
      'Furnishing': 'فرنشنگ',
      'Bedrooms': 'بیڈروم',
      'Bathrooms': 'باتھ روم',
      'Area (sqft)': 'رقبہ (sqft)',
      'Seller Name': 'سیلر کا نام',
      'Phone': 'فون',
      'Amenities (comma separated)': 'سہولیات (کاما سے الگ)',
      'Brand': 'برانڈ',
      'Model': 'ماڈل',
      'Condition': 'حالت',
      'Storage': 'اسٹوریج',
      'RAM': 'RAM',
      'Age': 'عمر',
      'Screen Size': 'اسکرین سائز',
      'Color': 'رنگ',
      'Warranty': 'وارنٹی',
      'Battery Health': 'بیٹری ہیلتھ',
      'Version': 'ورژن',
      'Damage / Defects': 'نقصان / خرابی',
      'Seller Type': 'سیلر کی قسم',
      'Rental Duration': 'کرایہ کی مدت',
      'Make (Brand)': 'میک (برانڈ)',
      'Year': 'سال',
      'Mileage (km)': 'مائلیج (km)',
      'Transmission': 'ٹرانسمیشن',
      'Fuel Type': 'فیول ٹائپ',
      'Body Type': 'باڈی ٹائپ',
      'Exterior Color': 'بیرونی رنگ',
      'Currency': 'کرنسی',
      'City': 'شہر',
      'Address': 'پتہ',
      'Post Ad': 'اشتہار پوسٹ کریں',
      'Photos': 'تصاویر',
      'Add Photo': 'تصویر شامل کریں',
      'Cover': 'کور',
      'Choose from Gallery': 'گیلری سے منتخب کریں',
      'Take a Photo': 'تصویر لیں',
      'First photo will be the cover. Tap + to add up to 10 photos.':
          'پہلی تصویر کور ہوگی۔ 10 تک تصاویر شامل کریں.',
      // Common
      'no_listings_yet': 'کوئی لسٹنگ نہیں ہے',
      'error': 'خرابی',
      'success': 'کامیابی',
      'loading': 'لوڈ ہو رہا ہے...',
      'delete': 'حذف کریں',
      'save': 'محفوظ کریں',
      'edit': 'ترمیم کریں',
      'add': 'شامل کریں',
      'done': 'مکمل',
      'yes': 'ہاں',
      'no': 'نہیں',
      'ok': 'ٹھیک ہے',
      // Chat
      'say_hi_to_start': 'چیٹ شروع کرنے کے لیے سلام کہیں',
      'seen': 'دیکھا گیا',
      'delete_chat': 'چیٹ حذف کریں',
      'your_chat_is_empty': 'آپ کی چیٹ خالی ہے!',
      'open_listing_and_tap_chat': 'لسٹنگ کھولیں اور Chat دبائیں',
      'explore_listings': 'لسٹنگز دیکھیں',
      'block_user': 'صارف کو مسدود کریں',
      'unblock_user': 'صارف کو کھولیں',
      'user_blocked_chat_disabled': 'صارف مسدود ہے۔ چیٹ غیر فعال ہے۔',
      'user_unblocked_chat_enabled': 'صارف کھولا گیا۔ چیٹ فعال ہے۔',
      'report_user': 'صارف کو رپورٹ کریں',
      'report_submitted': 'ایڈمن کو رپورٹ بھیجی گئی۔',
      'chat_listing': 'چیٹ لسٹنگ',
      // Profile
      'profile_name': 'پروفائل کا نام',
      'displayed_on_profile': 'یہ آپ کے پروفائل پر دکھایا جاتا ہے',
      'account_details': 'اکاؤنٹ کی تفصیلات',
      'not_visible_to_others': 'یہ دوسروں کو نظر نہیں آتا',
      'save_changes': 'تبدیلیاں محفوظ کریں',
      'profile_saved_successfully': 'پروفائل کامیابی سے محفوظ ہو گیا!',
      'failed_to_save': 'محفوظ کرنا ناکام',
      'first_name': 'پہلا نام',
      'last_name': 'آخری نام',
      'date_of_birth': 'پیدائش کی تاریخ',
      'select_date_of_birth': 'پیدائش کی تاریخ منتخب کریں',
      'nationality': 'قومیت',
      'select_nationality': 'قومیت منتخب کریں',
      'gender': 'جنس',
      'select_gender': 'جنس منتخب کریں',
      'male': 'مرد',
      'female': 'عورت',
      'prefer_not_to_say': 'کہنا پسند نہیں',
      'update_password': 'پاس ورڈ اپڈیٹ کریں',
      'deactivate': 'غیر فعال کریں',
      'delete_account_confirm': 'اکاؤنٹ حذف کریں',
      'blocked_users_list': 'مسدود صارفین',
      'no_blocked_users': 'کوئی مسدود صارف نہیں ہے',
      'unblock': 'کھولیں',
      'push_notifications': 'پش اطلاعات',
      'enable_all_notifications': 'تمام اطلاعات فعال کریں',
      'upload_failed': 'اپ لوڈ ناکام',
      // Auth
      'full_name': 'مکمل نام',
      'enter_full_name': 'اپنا مکمل نام درج کریں',
      'name_required': 'نام ضروری ہے',
      'email_required': 'ای میل ضروری ہے',
      'valid_email_required': 'درست ای میل درج کریں',
      'phone_number': 'فون نمبر',
      'eg_phone': 'مثال +93700000000',
      'password_required': 'پاس ورڈ ضروری ہے',
      'min_6_characters': 'کم از کم 6 حروف',
      'select_country_code': 'ملک کوڈ منتخب کریں',
      'send_code': 'کوڈ بھیجیں',
      'enter_verification_code': 'تصدیق کوڈ درج کریں',
      'submit': 'جمع کریں',
      'welcome_back': 'خوش آمدید',
      'sign_in_to_account': 'اپنے اکاؤنٹ میں سائن ان کریں',
      'afghanistan': 'افغانستان',
      'pakistan': 'پاکستان',
      'iran': 'ایران',
      'india': 'بھارت',
      'bangladesh': 'بنگلہ دیش',
      'turkey': 'ترکی',
      'saudi_arabia': 'سعودی عرب',
      'oman': 'عمان',
      'qatar': 'قطر',
      'ksa': 'سعودی عرب',
      'syria': 'شام',
      'uae_short': 'یو اے ای',
      'uae': 'متحدہ عرب امارات',
      'usa': 'ریاستہائے متحدہ',
      'uk': 'برطانیہ',
      'china': 'چین',
      'russia': 'روس',
      'germany': 'جرمنی',
      'france': 'فرانس',
      'canada': 'کینڈا',
      'australia': 'آسٹریلیا',
      'japan': 'جاپان',
      'korea': 'جنوبی کوریا',
      'malaysia': 'ملیشیا',
      'indonesia': 'انڈونیشیا',
      'egypt': 'مصر',
      'nigeria': 'نائجیریا',
      'kenya': 'کینیا',
      'south_africa': 'جنوبی افریقہ',
      'other': 'دیگر',
      // Admin
      'all_chats': 'تمام چیٹس',
      'access_denied': 'رسائی مسترد',
      'no_chats_yet': 'ابھی کوئی چیٹ نہیں ہے۔',
      'no_messages_yet': 'ابھی کوئی پیغام نہیں۔',
      'buyer': 'خریدار',
      'classifieds_dashboard': 'درجہ بندی ڈیش بورڈ',
      'items': 'اشیاء',
      'no_listings': 'کوئی لسٹنگ نہیں',
      'admin_dashboard': 'ایڈمن ڈیش بورڈ',
      'supabase_sql_setup': 'Supabase SQL سیٹ اپ',
      'filter_options': 'فلٹر کے اختیارات',
      'no_options_added_yet': 'ابھی کوئی اختیار شامل نہیں کیا گیا',
      'tap_plus_to_add': 'فلٹر ویلیوز شامل کرنے کے لیے ٹیپ کریں',
      'add_option': 'اختیار شامل کریں',
      'category': 'کیٹیگری',
      'type': 'قسم',
      'edit_option': 'اختیار ترمیم کریں',
      'this_option_will_be_removed': 'یہ اختیار ہٹایا جائے گا۔',
      'inactive': 'غیر فعال',
      'table_not_found': 'ٹیبل نہیں ملا۔ پہلے SQL سیٹ اپ چلائیں۔',
      'retry': 'دوبارہ کوشش کریں',
      'price_settings': 'قیمت کی ترتیبات',
      'save_all_settings': 'تمام ترتیبات محفوظ کریں',
      'settings_saved': 'ترتیبات محفوظ ہو گئیں!',
      'regions_cities': 'علاقے اور شہر',
      'run_sql_setup_first': 'پہلے ایڈمن ڈیش بورڈ سے SQL سیٹ اپ چلائیں۔',
      'no_regions_added_yet': 'ابھی کوئی علاقہ شامل نہیں کیا گیا',
      'tap_plus_to_add_region': 'علاقہ شامل کرنے کے لیے ٹیپ کریں',
      'add_region': 'علاقہ شامل کریں',
      'edit_region': 'علاقہ ترمیم کریں',
      'active': 'فعال',
      'delete_region': 'علاقہ حذف کریں؟',
      'no_cities_added': 'کوئی شہر شامل نہیں کیا گیا',
      'manage_cities': 'شہروں کو منظم کریں',
      'no_cities_yet': 'ابھی کوئی شہر نہیں',
      'save_cities': 'شہروں کو محفوظ کریں',
      // Sell/Listing
      'post_car_ad': 'کار کا اشتہار پوسٹ کریں',
      'select_currency': 'کرینسی منتخب کریں',
      'photos': 'تصاویر',
      'more': 'مزید',
      'post_mobile_ad': 'موبائل کا اشتہار پوسٹ کریں',
      'post_property_ad': 'پراپرٹی کا اشتہار پوسٹ کریں',
      'add_field': 'فیلڈ شامل کریں',
      'gallery': 'گیلری',
      'camera': 'کیمرہ',
      'search_failed': 'تلاش ناکام',
      // Categories
      'top_deals': 'بہترین ڈیلز',
      'see_all': 'سب دیکھیں',
      'featured': 'خصوصی',
      'sort': 'ترتیب دیں',
      'share': 'شیئر کریں',
      'shared': 'شیئر کیا',
      'jobs': 'نوکریاں',
      'experience': 'تجربہ',
      'books_sports': 'کتابیں اور کھیل',
      'no_jobs_found': 'کوئی نوکری نہیں ملی',
      'max_salary': 'زیادہ سے زیادہ تنخواہ',
      'min_salary': 'کم سے کم تنخواہ',
      'max_price': 'زیادہ سے زیادہ قیمت',
      'min_price': 'کم سے کم قیمت',
      // Detail screens
      'car_overview': 'کار کا جائزہ',
      'listing_not_found': 'فہرست نہیں ملی',
      'go_back': 'واپس جائیں',
      'car_detail_not_available': 'کار تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'property_detail_not_available': 'پراپرٹی تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'mobile_detail_not_available': 'موبائل تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'electronics_detail_not_available': 'الیکٹرانکس تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'furniture_detail_not_available': 'فرنیچر تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'jobs_detail_not_available': 'نوکری تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'classifieds_detail_not_available': 'درجہ بندی تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'spare_parts_detail_not_available': 'حصہ تفصیل سکرین اضافی سیٹ اپ کی ضرورت ہے',
      'detail_not_available': 'یہ زمرہ تفصیل سکرین دستیاب نہیں ہے',
      'copied_text': 'نقل: {text}',
      'share_via_message': 'پیغام کے ذریعے شیئر کریں',
      'link_copied': 'لنک نقل {text}',
      'check_out_listing': 'اس کار کو دیکھیں: {text} - {price} on Afghan Deals Pro',
    },
  };
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((item) => item.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
